name: Tests Runner
on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Instal dependencies
        run: pipenv sync --dev

      - name: Run pytest
        run: pipenv run pytest -v
